### PR TITLE
Feat: Add working-directory field so you can release a sub-dir Rust project

### PR DESCRIPTION
**Pull request by Snoupix**
Follow up of the closed PR #2.

### CODE REVIEW

**Comment by autarch** [comment]
Ok, _this_ time I was able to push. I think it was definitely because the forked repo's PR was based on the `v0` branch.

**Comment by Snoupix** [comment]
Perfect, thank you for your time !
To me both of the PRs were based on the `v0` branch but this time I created a branch for the PR. I don't know.

**Comment by autarch** [comment]
> Perfect, thank you for your time ! To me both of the PRs were based on the `v0` branch but this time I created a branch for the PR. I don't know.

If you use the default branch in _your_ fork as the basis for the PR, GitHub doesn't let me push to it. I think that makes sense, though I don't think it's well-documented.

**Comment by Snoupix** [comment]
Hum yes, it makes sense. Well, we learned something :)

**Comment by autarch** [comment]
Thanks for working through this with me.

**Pull request merged**
